### ISSUE TITLE
Template will not depoy

### ISSUE THREAD

**Issue by jeffmoore64** [Azure/Vector-Search-AI-Assistant#11]
The following error occurs when this is deployed in US East.
I have deleted all openAI resources and purged them.  Still get this error.  There is zero information I have found that is helpful in resolving this on the internet.

Another operation is being performed on the parent resource '/subscriptions/xxx-xxx-xxx-xxx-xxx/resourceGroups/CosmosRAG1/providers/Microsoft.CognitiveServices/accounts/jeffmoore-openai'. Please try again later. (Code: RequestConflict)

**Comment by jeffmoore64** [comment]
It doesn't matter what region I deploy in I get the same error as listed above.

Interestingly if I hard code a different supported region then I get an error stating that S0 (standard) is not a valid option, yet I can create that very resource manually in the region I've specified, eg eastus2

**Comment by markjbrown** [comment]
This was fixed by modifying the ARM template to have the models deploy one at a time by putting a `dependsOn` in the template.
