### ISSUE TITLE
Upgrade model GPT-3.5 '0301'

### ISSUE THREAD

**Issue by lukemurraynz** [Azure/Vector-Search-AI-Assistant#37]
Upgrade model GPT-3.5 '0301'

0301 is not available in as many Regions as 0613, i.e. AustraliaEast and on the chopping block.

"Version 0613 of gpt-35-turbo and gpt-35-turbo-16k will be retired no earlier than June 13, 2024. Version 0301 of gpt-35-turbo will be retired no earlier than July 5, 2024. See [model updates](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/working-with-models#model-updates) for model upgrade behavior."

So plan for later model, potentially: 1106.

Reference: [GPT-3.5 models](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models?WT.mc_id=AZ-MVP-5004796#gpt-35-models)

**Comment by markjbrown** [comment]
Closing. This has been resolved.
