### ISSUE TITLE
 the documented appsettings.Development.json on the readme.md does not match what is expected with the second Cosmos DB account.

### ISSUE THREAD

**Issue by emmanueldeletang** [Azure/Vector-Search-AI-Assistant#56]
@markjbrown  @joelhulen @ciprianjichici 

In the ChatAPI project, create an appsettings.Development.json file with the following content (replace all <...> placeholders with the values from your deployment):

{
    "MSCosmosDBOpenAI": {
        "OpenAI": {
            "Endpoint": "[https://%3c...%3e.openai.azure.com/]https://<...>.openai.azure.com/",
            "Key": "<...>"
        },
        "CosmosDB": {
            "Endpoint": "[https://%3c...%3e.documents.azure.com:443/]https://<...>.documents.azure.com:443/",
            "Key": "<...>"
        },
        "DurableSystemPrompt": {
            "BlobStorageConnection": "<...>"
        },
        "BlobStorageMemorySource": {
            "ConfigBlobStorageConnection": "<...>"
        }
    }
}
With this is not work because you have to add for cosmosdbVectorstore too , so it will should be 😂

{
    "MSCosmosDBOpenAI": {
        "OpenAI": {
            "Endpoint": "[https://%3c...%3e.openai.azure.com/]https://<...>.openai.azure.com/",
            "Key": "<...>"
        },
        "CosmosDB": {
            "Endpoint": "[https://%3c...%3e.documents.azure.com:443/]https://<...>.documents.azure.com:443/",
            "Key": "<...>"
        },
"CosmosDBVectorStore": {
            "Endpoint": "[https://%3c...%3e.documents.azure.com:443/]https://<...>.documents.azure.com:443/",    
        "Key": "<...>"
},
        "DurableSystemPrompt": {            "BlobStorageConnection": "<...>"        },
        "BlobStorageMemorySource": {            "ConfigBlobStorageConnection": "<...>"        }    } }

**Comment by alekseys** [comment]
fixed by adding the CosmosDBVectorStore to appsettings.Development.json instructions. Tested locally

**Comment by alekseys** [comment]
fixed by adding the CosmosDBVectorStore to appsettings.Development.json instructions. Tested locally
