### ISSUE TITLE
Config values don't match for local debug

### ISSUE THREAD

**Issue by markjbrown** [Azure/Vector-Search-AI-Assistant#7]
The config values for appsettings.Development.json do not match what is expected in the app. View in [run locally and debug](https://github.com/markjbrown/Vector-Search-AI-Assistant/tree/cognitive-search-vector#run-locally-and-debug).

Then see what the code is expecting on startup in the ChatServiceWebApi.  The result here is Cog Search will not connect because the config values are empty.

<img width="501" alt="image" src="https://github.com/Azure/Vector-Search-AI-Assistant/assets/800166/b74e88b5-4373-44f6-b7ba-bd086e952588">

**Comment by markjbrown** [comment]
i tried updating appsettings.Development.json to this (see below) which I'm guessing is not what you intended.


{
  "MSCosmosDBOpenAI": {
    "CognitiveSearchMemorySource": {
      "Endpoint": "<endpoint>",
      "Key": "<key>"
    },
    "CognitiveSearch": {
      "Endpoint": "<endpoint>",
      "Key": "<key>"
    },
    "OpenAI": {
      "Endpoint": "<endpoint>",
      "Key": "<key>"
    },
    "CosmosDB": {
      "Endpoint": "<endpoint>",
      "Key": "<key>"
    },
    "BlobStorageMemorySource": {
      "ConfigBlobStorageConnection": "<connection string>"
    },
    "DurableSystemPrompt": {
      "BlobStorageConnection": "<connection string>"
    }
  }
}

**Comment by markjbrown** [comment]
@joelhulen @ciprianjichici I got debug working but I'm guessing this appsettings is not what you intended.

**Comment by alekseys** [comment]
Same issue here on fresh clone - exceptions are thrown about Key being null at the start of the debugging session. I had to add the following two sections to appSettings.development.json:

		"BlobStorageMemorySource": {
			"ConfigBlobStorageConnection": "..."
		},
		"CognitiveSearchMemorySource": {
			"Endpoint": "...",
			"Key": "..."
		}


Please note these are repetitive of two other sections already in this file. For the time being I've made the change to debugging instructions in readme.md but the code has to be cleaned up to avoid the duplicity.

**Comment by markjbrown** [comment]
Hey alekseys I'll take care of it. Thanks though 🙂

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
