### ISSUE TITLE
Entering holding pattern to wait for proper backend API initialization loop

### ISSUE THREAD

**Issue by EricDatacomNZ** [Azure/Vector-Search-AI-Assistant#9]
Entering holding pattern to wait for proper backend API initialization
Attempting to retrieve status from https://**.eastus.aksapp.io/api/status every 20 seconds with 50 retries

I've attempted to deploy making use of both deployment-standard.md and deployment-cloudshell.md, both resulting in the same outcome. Is this a bug or am I doing something wrong?

**Comment by markjbrown** [comment]
This may be because Docker Desktop is not actively running on your machine (same thing happened to me). Retry with the standard deployment after double checking it's running and let me know.

**Comment by EricDatacomNZ** [comment]
> This may be because Docker Desktop is not actively running on your machine (same thing happened to me). Retry with the standard deployment after double checking it's running and let me know.

Thank you for the response! I have Docker Desktop open, not sure if running it on MacOS makes a difference?

I can see the script creating two local images on Docker during the deployment process, but it still ends up failing.

**Comment by markjbrown** [comment]
Should work ok on Mac I would think. There's nothing Windows specific to any of this. 

Are you seeing any warnings or other errors further up in the install output in your terminal?

**Comment by EricDatacomNZ** [comment]
> Should work ok on Mac I would think. There's nothing Windows specific to any of this.
> 
> Are you seeing any warnings or other errors further up in the install output in your terminal?

No, the only warning I get, not sure if it's of much relevance is: WARNING: Command group 'az storage' is in preview and under development.

Other than that, no errors at all. I tried using the standard deployment process locally and cloudshell directly on Azure, both deployments fail at the same point for some reason.

**Comment by markjbrown** [comment]
I'm assuming you are deploying to Azure Container Apps. Can you go to Azure Portal and in the resource group for your deployment, find the container app with a name that ends with 'chatapiaca' and see what the status is?

![image](https://github.com/Azure/Vector-Search-AI-Assistant/assets/800166/aa16553d-7daf-4047-99fd-84c4cacce95e)

**Comment by EricDatacomNZ** [comment]
These are the only deployed services I have. I just reran the deployment script again, and got stuck at the same loop

![Screenshot 2023-10-04 at 11 43 22](https://github.com/Azure/Vector-Search-AI-Assistant/assets/143041259/e58e5fc6-aad5-4e8e-978f-202e3417c334)

**Comment by markjbrown** [comment]
@alekseys or @sesmyrnov have either of you guys experienced this before with AKS deployment for this sample?

**Comment by sesmyrnov** [comment]
Yes - I have seen this same behavior a while ago before when deploying  older version ( from the old repo with AKS being main deployment). This was fixed and I believe workaround/fix for this was to have a docker running.  I had several successful deployments in last couple of weeks with AKS before last set of updates (Windows) - but have not tried to do ACA deployment yet for this one. This deployment seems to be doing AKS - so may be try to turn off AKS and do ACA to test if that will work.

**Comment by markjbrown** [comment]
Agreed. AKS has been problematic for us. Is there any chance you can try doing the default deployment instead without the -aks 1 in the PS script?

**Comment by markjbrown** [comment]
This has been resolved. Closing.
